"""empty message

Revision ID: b626ddfd7233
Revises: 
Create Date: 2025-08-26 16:07:08.580044

"""
from typing import Sequence, Union

import sqlalchemy as sa

# To fix the error:
# sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
#                    ^^^^^^^^
# NameError: name 'sqlmodel' is not defined.
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b626ddfd7233'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_title'), 'task', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_title'), table_name='task')
    op.drop_table('task')
    # ### end Alembic commands ###
